# Generated by Django 6.0.4 on 2026-04-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube embed URL e.g. https://www.youtube.com/embed/VIDEO_ID",
            ),
        ),
    ]
